name: Teste de Desempenho

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Instalar Dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xzf apache-jmeter-5.4.1.tgz

    - name: Executar Testes do JMeter
      run: apache-jmeter-5.4.1/bin/jmeter -n -t ./test_plan.jmx -l results.jtl

    - name: Upload de Resultados
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: results.jtl
