name: Teste de Desempenho

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Instalar Dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget
        wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz

    - name: Create reports directory
      run: mkdir reports
 
    - name: JMeter Test
      run: |
        ./apache-jmeter-5.6.3/bin/jmeter -n -t "./Requisição HTTP.jmx" -l "./results.jtl" -e -o "./reports/html/"
    
    - name: Upload de Resultados
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.jtl
        if-no-files-found: error

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-html-reports
        path: reports
        if-no-files-found: error
